# Generated by Django 4.0 on 2023-02-16 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='tier_type',
            field=models.IntegerField(default=3, editable=False),
        ),
        migrations.AlterField(
            model_name='tier',
            name='thumb1_H',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tier',
            name='thumb1_W',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tier',
            name='thumb2_H',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='tier',
            name='thumb2_W',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 16, 21, 58, 996874), editable=False),
        ),
    ]
