# Generated by Django 4.0 on 2023-02-16 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_tier_tier_type_alter_tier_thumb1_h_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 16, 22, 3, 80108), editable=False),
        ),
    ]
