# Generated by Django 4.0 on 2023-02-16 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_userimage_upload_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tier_type',
            new_name='tier',
        ),
        migrations.AlterField(
            model_name='tier',
            name='tier_type',
            field=models.IntegerField(default=4, editable=False),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='exp_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='img_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 18, 33, 53, 289546), editable=False),
        ),
    ]
