# Generated by Django 4.0 on 2023-02-16 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_rename_tier_type_user_tier_alter_tier_tier_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tier',
            new_name='tier_t',
        ),
        migrations.AlterField(
            model_name='userimage',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 18, 44, 35, 290266), editable=False),
        ),
    ]
