# Generated by Django 4.0 on 2023-02-16 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_rename_tier_user_tier_t_alter_userimage_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='tier_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='thumb_1',
            field=models.ImageField(editable=False, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='thumb_2',
            field=models.ImageField(blank=True, editable=False, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 19, 49, 7, 303733), editable=False),
        ),
    ]
