# Generated by Django 4.0 on 2023-02-17 13:51

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_userimage_tier_type_alter_userimage_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='thumb_1_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userimage',
            name='thumb_2_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, editable=False, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='img',
            field=models.ImageField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 17, 14, 51, 31, 361420), editable=False),
        ),
    ]
