# Generated by Django 4.0 on 2023-02-18 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_alter_userimage_token_alter_userimage_upload_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimage',
            name='img_link',
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='thumb_1_link',
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='thumb_2_link',
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='tier_type',
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='token',
        ),
        migrations.AddField(
            model_name='userimage',
            name='hash',
            field=models.CharField(default='oFp6Y0Q1by', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 18, 12, 23, 54, 539996), editable=False),
        ),
    ]
