# Generated by Django 4.0 on 2023-02-18 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_remove_userimage_img_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='hash',
            field=models.CharField(default='jq2dobxt61', editable=False, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 18, 12, 44, 8, 170411), editable=False),
        ),
    ]
