# Generated by Django 4.0 on 2023-02-18 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_alter_userimage_hash_alter_userimage_upload_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimage',
            name='hash',
        ),
        migrations.AlterField(
            model_name='userimage',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 18, 12, 50, 3, 324725), editable=False),
        ),
    ]
