# Generated by Django 4.0 on 2023-02-18 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_remove_userimage_hash_alter_userimage_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 18, 12, 52, 51, 719357), editable=False),
        ),
    ]
